# Generated by Django 3.2.6 on 2022-07-05 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_alter_requirement_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 5, 16, 48, 19, 494482)),
        ),
    ]
