# Generated by Django 3.2.6 on 2022-07-07 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_department'),
        ('management', '0021_merge_20220706_1215'),
    ]

    operations = [
    ]
