# Generated by Django 3.2.6 on 2022-07-07 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_merge_0021_department_0021_merge_20220706_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklinks',
            name='added_by',
        ),
        migrations.AlterField(
            model_name='tasklinks',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tasklinks',
            name='link_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='tasklinks',
            name='task',
        ),
        migrations.AddField(
            model_name='tasklinks',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_featured', to='management.task'),
        ),
    ]
