# Generated by Django 3.2.6 on 2022-07-05 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_department'),
        ('accounts', '0003_merge_0002_auto_20220630_0350_0002_auto_20220630_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Required', max_length=255, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='category safe URL')),
                ('description', models.TextField(default=None, max_length=1000)),
                ('entry_date', models.DateTimeField(auto_now_add=True, verbose_name='entered on')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('department', models.ForeignKey(default='Other', on_delete=django.db.models.deletion.RESTRICT, to='management.department')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=255, verbose_name='credential Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='credential safe URL')),
                ('description', models.TextField(default=None, max_length=1000)),
                ('link_name', models.CharField(default='General', max_length=255)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, default='No Password Needed', max_length=255, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True, verbose_name='entered on')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(blank=True, related_name='credentialcategory', to='accounts.CredentialCategory')),
            ],
            options={
                'verbose_name_plural': 'credentials',
            },
        ),
    ]
